[build]
builder = "NIXPACKS"
buildCommand = "cd backend && bash ./mvnw -DskipTests package"

[deploy]
startCommand = "java -jar backend/target/backend-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 60
